package ghostty

import (
	"bytes"
	"fmt"
	"io"
	"strings"

	"github.com/yolocs/styles/yolodev/internal/theme"
)

func Render(w io.Writer, value theme.Theme) error {
	diagnostics := theme.Validate(value)
	if theme.HasErrors(diagnostics) {
		var messages []string
		for _, diagnostic := range diagnostics {
			if diagnostic.Severity == theme.Error {
				messages = append(messages, diagnostic.Field+": "+diagnostic.Message)
			}
		}
		return fmt.Errorf("render Ghostty theme: invalid terminal theme: %s", strings.Join(messages, "; "))
	}

	value = theme.Normalize(value)
	var output bytes.Buffer
	fmt.Fprintln(&output, "# Generated by yolodev from canonical terminal-theme TOML.")
	palette := append(value.Palette.Normal.Values(), value.Palette.Bright.Values()...)
	for index, color := range palette {
		fmt.Fprintf(&output, "palette = %d=%s\n", index, color)
	}
	fmt.Fprintf(&output, "background = %s\n", value.Colors.Background)
	fmt.Fprintf(&output, "foreground = %s\n", value.Colors.Foreground)
	fmt.Fprintf(&output, "cursor-color = %s\n", value.Colors.Cursor)
	fmt.Fprintf(&output, "cursor-text = %s\n", value.Colors.CursorText)
	fmt.Fprintf(&output, "selection-background = %s\n", value.Colors.SelectionBackground)
	fmt.Fprintf(&output, "selection-foreground = %s\n", value.Colors.SelectionForeground)

	if _, err := io.Copy(w, &output); err != nil {
		return fmt.Errorf("write Ghostty theme: %w", err)
	}
	return nil
}
